[package]
name = "lsendctl"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ipc = { path = "../ipc" }
anyhow = "1.0"
clap = { version = "4", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "io-util"] }
