[package]
name = "lsendd"
version.workspace = true
edition.workspace = true

[dependencies]
localsend = { git = "https://github.com/localsend/localsend", package = "localsend", rev = "e768240d1ad95f0f162b852b5ff37bec71cde1ef", features = ["discovery", "http"] }
ipc = { path = "../ipc" }
anyhow = "1.0"
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "net", "io-util", "fs"] }
tokio-util = { version = "0.7", features = ["rt"] }
uuid = { version = "1", features = ["v4"] }
mime_guess = "2.0"
